--  --------------------------------------------OFFERS INSERTIONS-------------------------------------------------

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (11,8,1, 15343); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (39,1,1, 22751); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (14,9,1, 74080); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (19,1,1, 53440); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (18,3,1, 92240);  
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (43,6,1, 37920); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (34,1,1, 39391); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (18,5,1, 27255); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (9,3,1, 53792); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (48,3,1, 72681); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (37,2,1, 76721); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (39,3,1, 36342); 
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (6,5,1, 54510); 

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (37,9,2, 61375 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (43,7,2, 90850 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (25,1,2, 75830 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (6,9,2, 61376 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (35,6,2, 53441 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (20,7,2, 92065 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (7,4,2, 76544 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (19,9,2, 14816 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (17,6,2, 36341 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (7,4,2, 53790 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (6,6,2, 54511 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (7,9,2, 90200 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (5,1,2, 84128 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (7,1,2, 15168 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (17,8,2, 75840 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`)  VALUES (12,1,2, 30336 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (19,9,3, 37920 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (26,8,3, 76895 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (14,8,3, 61200 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (27,9,3, 75820 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (10,4,3, 53440 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (30,9,3, 53792 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (21,1,3, 76720 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (43,9,3, 38448 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (23,9,3, 68961 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (11,8,3, 69695 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (23,9,3, 84480 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,2,3, 48475 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (14,2,3, 69136 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (28,4,4, 15121 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (22,9,4, 15169 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (42,2,4, 92064 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (29,4,4, 46032 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (18,1,4, 76721 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (46,9,4, 30689 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (14,9,4, 22751 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (31,1,4, 76896 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,6,4, 75830 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (12,2,4, 38272 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (43,6,4, 61377 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (41,6,4, 27255 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (24,5,4, 57560 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (18,3,4, 90856 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (35,7,4, 36341 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (10,3,4, 72681 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (29,8,4, 53790 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,2,4, 96950 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,4,4, 74080 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (19,9,4, 18170 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (20,9,4, 78780 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (13,4,4, 61376 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (33,7,4, 18172 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (15,4,4, 36342 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (16,7,4, 63595 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (43,8,4, 54510 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (30,7,5, 46032 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (46,8,5, 57561 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (16,7,5, 22753 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,9,5, 15169 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (39,1,5, 57560 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (42,1,5, 76896 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (46,4,5, 69136 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (30,8,5, 37920 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (35,5,5, 63595 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (24,1,5, 92241 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (10,8,5, 76544 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (35,2,5, 75730 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (49,4,5, 15344 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (34,7,5, 75820 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (23,4,5, 45425 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (3,7,5, 36341 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (9,3,5, 96950 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (50,6,5, 61376 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (1,5,5, 30686 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (34,3,5, 53790 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,3,5, 75840 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (45,8,5, 69695 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,3,5, 76720 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (7,1,5, 15168 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (13,9,5, 22751 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (20,1,5, 53440 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (20,3,5, 74080 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (27,9,5, 93900 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (17,5,5, 15120 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (30,8,6, 18172 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (28,3,6, 53792 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (42,9,6, 53791 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (1,9,6, 63595 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (50,3,6, 22753 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (5,3,6, 36341 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,7,6, 27255 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (22,7,6, 92241 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (20,6,6, 72681 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (14,6,6, 68961 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (5,4,6, 15168 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (14,5,6, 96950 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (32,1,6, 45680 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (23,1,6, 36342 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (1,1,6, 30336 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (7,7,6, 22752 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (4,6,6, 15120 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (8,4,6, 15344 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (27,8,6, 46032 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (2,9,6, 54511 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,5,6, 45504 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (28,6,6, 76896 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (6,7,7, 69695 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (22,7,7, 39391 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (45,1,7, 75820 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (23,8,7, 38448 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (10,1,7, 36341 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (37,9,7, 84481 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (16,8,7, 15121 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (48,7,7, 30687 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (3,8,7, 96950 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (2,6,7, 92241 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (39,7,7, 76895 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,5,7, 15344 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (32,1,7, 57560 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (22,1,7, 53792 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (3,2,7, 30686 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (43,3,7, 15169 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (25,6,7, 76896 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (16,3,7, 18172 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (2,8,8, 48475 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (45,5,8, 53440 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (46,3,8, 75730 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (2,5,8, 96951 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (28,4,8, 57560 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,4,8, 84481 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (42,3,8, 36341 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (30,7,8, 37920 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (34,5,8, 75830 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (41,5,8, 53790 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (10,3,8, 76720 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,6,8, 30686 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (7,7,8, 76896 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (40,9,8, 61200 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (26,8,8, 39390 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (44,2,8, 15121 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (4,7,9, 14816 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (33,2,9, 61375  );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (18,4,9, 39390 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (5,9,9, 30688 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (37,8,9, 75840 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (35,4,9, 53792 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (23,4,9, 36340 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (17,4,9, 96950 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (25,3,9, 78781 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (34,6,9, 22753 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (40,8,9, 69136 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (48,6,9, 69695 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (20,5,9, 75830 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (18,2,9, 38272 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (19,5,9, 30687 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (12,8,9, 57560 );

INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (22,2,10, 72681 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (36,4,10, 63595 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (13,4,10, 22751 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (39,1,10, 76720 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (48,8,10, 45425 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (4,2,10, 84480 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (37,3,10, 76721 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (46,8,10, 30689 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (13,8,10, 61377 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (4,6,10, 30336 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (37,6,10, 96951);
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (28,4,10, 36340 );
INSERT INTO `Offers` (`Alley#`, `Shelf#`, `Store_id`, `Barcode`) VALUES (37,6,10, 92064 );